# Generated by Django 5.1.5 on 2025-02-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='importance',
            field=models.CharField(choices=[('trivial', 'Trivial'), ('important', 'Important'), ('high_priority', 'High Priority'), ('very_important', 'Very Important')], default='trivial', max_length=30),
        ),
    ]
