# Generated by Django 5.1.5 on 2025-02-09 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('base', '0004_subtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskroom',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='admin_rooms', to='accounts.profile'),
            preserve_default=False,
        ),
    ]
