# Generated by Django 5.1.5 on 2025-02-23 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='task',
        ),
        migrations.AddField(
            model_name='notes',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='base.taskroom'),
            preserve_default=False,
        ),
    ]
