# Generated by Django 5.1.5 on 2025-02-23 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_notes_task_notes_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='base.taskroom'),
        ),
    ]
