# Generated by Django 5.1.5 on 2025-02-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_notes_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='isMarked',
            field=models.BooleanField(default=False),
        ),
    ]
