# Generated by Django 5.1.7 on 2025-03-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_task_ismarked'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='background_color',
            field=models.CharField(default='#FFE68E', max_length=20),
        ),
    ]
