# Generated by Django 5.2 on 2025-04-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_subtask_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='something',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
