# Generated by Django 5.2 on 2025-04-03 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_subtask_something'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='something',
        ),
    ]
