# Generated by Django 5.2 on 2025-04-03 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_subtask_something'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='isMarked',
            new_name='is_marked',
        ),
    ]
